In [1]:
1+1

2

In [2]:
%config Completer.use_jedi = False

In [3]:
import numpy as np

In [4]:
my_list1 = [1,2,3]

In [6]:
arr1 = np.array(my_list1) #cast a python list into an array

In [8]:
arr1

array([1, 2, 3])

In [9]:
#casting a list of list into a 2D array i.e. a matrix

my_list2 = [[1,2,3], [4,5,6], [7,8,9]]

matrix1 = np.array(my_list2)

matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
#generate an array using arange function; similar to range function in Python; quickly produces a range

arr2 = np.arange(0, 10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#np.linspace --> returns evenly spaced numbers over a specified interval

arr3 = np.linspace(0,5,50)
arr3

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [13]:
#np.eye --> create an identical matrix; it is a 2D matrix

arr4 = np.eye(4)

arr4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
#generating random numpy arrays using random function

arr5 = np.random.rand(5) #1D array
arr5

arr6 = np.random.rand(3,4) #2D matrix
arr6

array([[0.8266258 , 0.60959976, 0.61449277, 0.07075495],
       [0.23612029, 0.32127035, 0.20311067, 0.18828583],
       [0.28470673, 0.84225009, 0.40594415, 0.14251028]])

In [15]:
#gives a new shape to an array without changing its data; no. of rows x no. of cols must be = no. of elements in array

arr7 = np.arange(0, 20)
arr7.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
#min() --> gets the minimum value of an array
#max() --> gets the maximum value of an array

arr5.min()

arr6.max()

0.01382467531016851

In [18]:
#argmax() --> find out the location of the max value in an array
#argmin() --> finds out the location of the min value in an array

arr6.argmax()

arr6.argmin()

3

In [19]:
#shape --> used to find out the shape of a vector

arr6.shape #(3,4) suggests that it is a 2 dimensional vector

(3, 4)