This notebook focuses on NumPy Array Indexing, Slicing

In [1]:
import numpy as np

In [2]:
%config Completer.use_jedi = False

In [16]:
#Much like Python Indexing starts at 0 

arr1 = np.arange(1, 16)

arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
arr1[8]

9

In [18]:
arr1[1:5] #if we want a set of elements, much like slicing in python [start index: ending index (not included)]

array([2, 3, 4, 5])

In [19]:
arr1[5:] #grabbing everything beyond index 5 

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
arr1[:6]

array([1, 2, 3, 4, 5, 6])

In [24]:
#broadcasting in an array --> changes the value of sliced indexes, this is called broadcasting

arr1[0:5] = 100
arr1

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15])

In [26]:
#fetching/selcting index value in a 2D array

arr2 = np.array([[29, 11, 1994], [30, 7, 1998], [24, 11, 1994]])

arr2

array([[  29,   11, 1994],
       [  30,    7, 1998],
       [  24,   11, 1994]])

In [30]:
#fetching 1994 from the above array

arr2[0][2] #array_name[row_index][col_index] or array_name[row_index, col_index]

#or

arr2[0,2]

1994

In [35]:
#selecting a part of array/subsection instead of a single element, this is called 2D array slicing
#you have to use sliced notation in order to do this

arr2[:2, 0:] #returns row 0 to 1 and from col 0 to all the way to the end


array([[  29,   11, 1994],
       [  30,    7, 1998]])

In [41]:
arr2[1:, 0:2]

array([[30,  7],
       [24, 11]])

In [43]:
#Conditional Selection

arr3 = np.arange(0, 11)

#[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

arr3 > 5 #returns a bool value comparies to the condition above and returns an array of bool values

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [45]:
bool_arr = arr3 > 5 #assigning the condition to a variable

bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [47]:
arr3[bool_arr] #returns values that satisfy the bool_arr condition

#or

arr3[arr3>5]

array([ 6,  7,  8,  9, 10])